# Generated by Django 4.2.16 on 2024-12-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_article_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/media/', verbose_name='Медиафайл'),
        ),
    ]
