# Generated by Django 4.2.16 on 2025-01-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
