# Generated by Django 4.2.16 on 2024-12-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Приветственный блок',
                'verbose_name_plural': 'Приветственные блоки',
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
